# -*- coding: utf-8 -*-
"""
/***************************************************************************
 CrossSectiotPlotterDialog
                                 A QGIS plugin
 CrossSectiotPlotter
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2020-08-31
        git sha              : $Format:%H$
        copyright            : (C) 2020 by NTUT
        email                : andy950702@gmail.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

import os

from qgis.PyQt import uic
from qgis.PyQt import QtWidgets

# This loads your .ui file so that PyQt can populate your plugin with the elements from Qt Designer
FirstPageClass, _ = uic.loadUiType(os.path.join(
    os.path.dirname(__file__), 'FirstPage.ui'))

PlotPageClass,_ = uic.loadUiType(os.path.join(
    os.path.dirname(__file__),'PlotPage.ui'))


class FirstPage(QtWidgets.QDialog, FirstPageClass):
    def __init__(self, parent=None):
        super(FirstPage, self).__init__(parent)
        self.setupUi(self)

class PlotPage(QtWidgets.QDialog, PlotPageClass):
    def __init__(self, parent=None):
        super(PlotPage, self).__init__(parent)
        self.setupUi(self)
